<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <!-- Swagger -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />

    <!-- Structured logging host integration -->
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NubeEra.Application\NubeEra.Application.csproj" />
    <ProjectReference Include="..\NubeEra.Infrastructure\NubeEra.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Filters\" />
    <Folder Include="Middlewares\" />
    <Folder Include="Models\" />
  </ItemGroup>

</Project>
