using AutoMapper;
using NubeEra.Application.DTOs;
using NubeEra.Domain.Entities;

namespace NubeEra.Application.Mappings;

/// <summary>AutoMapper profile for the School and Grade modules.</summary>
public class SchoolMappingProfile : Profile
{
    public SchoolMappingProfile()
    {
        // ── School ──────────────────────────────────────────────────────────
        CreateMap<School, SchoolDto>()
            .ForMember(dest => dest.FromGrade,     opt => opt.Ignore())  // Resolved by service via GradeLevel entity
            .ForMember(dest => dest.ToGrade,       opt => opt.Ignore())
            .ForMember(dest => dest.FromGradeName, opt => opt.Ignore())
            .ForMember(dest => dest.ToGradeName,   opt => opt.Ignore());

        CreateMap<SchoolCreateDto, School>()
            .ForMember(dest => dest.Id,            opt => opt.Ignore())
            .ForMember(dest => dest.IsActive,      opt => opt.MapFrom(_ => true))
            .ForMember(dest => dest.FromGradeId,   opt => opt.Ignore()) // Resolved by service
            .ForMember(dest => dest.ToGradeId,     opt => opt.Ignore())
            .ForMember(dest => dest.City,          opt => opt.Ignore())
            .ForMember(dest => dest.State,         opt => opt.Ignore())
            .ForMember(dest => dest.PostalCode,    opt => opt.Ignore())
            .ForMember(dest => dest.Country,       opt => opt.Ignore())
            .ForMember(dest => dest.EstablishedDate, opt => opt.Ignore())
            .ForMember(dest => dest.Website,       opt => opt.Ignore());

        CreateMap<SchoolUpdateDto, School>()
            .ForMember(dest => dest.Id,          opt => opt.Ignore())
            .ForMember(dest => dest.FromGradeId, opt => opt.Ignore())
            .ForMember(dest => dest.ToGradeId,   opt => opt.Ignore())
            .ForMember(dest => dest.City,        opt => opt.Ignore())
            .ForMember(dest => dest.State,       opt => opt.Ignore())
            .ForMember(dest => dest.PostalCode,  opt => opt.Ignore())
            .ForMember(dest => dest.Country,     opt => opt.Ignore())
            .ForMember(dest => dest.EstablishedDate, opt => opt.Ignore())
            .ForMember(dest => dest.Website,     opt => opt.Ignore());

        // ── Grade ───────────────────────────────────────────────────────────
        CreateMap<Grade, GradeDto>()
            .ForMember(dest => dest.SchoolName,        opt => opt.MapFrom(src => src.School != null ? src.School.Name : string.Empty))
            .ForMember(dest => dest.ClassTeacherName,  opt => opt.MapFrom(src => src.ClassTeacher != null
                ? $"{src.ClassTeacher.FirstName} {src.ClassTeacher.LastName}".Trim()
                : null))
            .ForMember(dest => dest.StudentCount,      opt => opt.MapFrom(src => src.Students != null ? src.Students.Count : 0));

        CreateMap<GradeCreateDto, Grade>()
            .ForMember(dest => dest.Id,           opt => opt.Ignore())
            .ForMember(dest => dest.GradeLevelId, opt => opt.Ignore()) // Resolved by service against grade_levels master
            .ForMember(dest => dest.GradeLevel,   opt => opt.Ignore()) // Derived from resolved master level
            .ForMember(dest => dest.GradeName,    opt => opt.Ignore()) // Generated by service
            .ForMember(dest => dest.IsActive,     opt => opt.MapFrom(_ => true))
            .ForMember(dest => dest.School,       opt => opt.Ignore())
            .ForMember(dest => dest.Level,        opt => opt.Ignore())
            .ForMember(dest => dest.ClassTeacher, opt => opt.Ignore())
            .ForMember(dest => dest.Students,     opt => opt.Ignore())
            .ForMember(dest => dest.Schedules,    opt => opt.Ignore())
            .ForMember(dest => dest.Exams,        opt => opt.Ignore());

        CreateMap<GradeUpdateDto, Grade>()
            .ForMember(dest => dest.Id,           opt => opt.Ignore())
            .ForMember(dest => dest.GradeLevelId, opt => opt.Ignore()) // Resolved by service against grade_levels master
            .ForMember(dest => dest.GradeLevel,   opt => opt.Ignore()) // Derived from resolved master level
            .ForMember(dest => dest.School,       opt => opt.Ignore())
            .ForMember(dest => dest.Level,        opt => opt.Ignore())
            .ForMember(dest => dest.ClassTeacher, opt => opt.Ignore())
            .ForMember(dest => dest.Students,     opt => opt.Ignore())
            .ForMember(dest => dest.Schedules,    opt => opt.Ignore())
            .ForMember(dest => dest.Exams,        opt => opt.Ignore());
    }
}
