using System.Threading;
using System.Threading.Tasks;
using Veriton.Application.Common.Reporting;

namespace Veriton.Application.Interfaces.Services.Reporting;

/// <summary>
/// The ONE export pipeline for every report (the directive's <c>ReportExportService</c>).
/// It is a thin orchestrator — NOT a second formatting engine: for Excel it
/// re-projects the already-RBAC-scoped <see cref="ReportResponseDto"/> rows into
/// the same <c>Dictionary&lt;string, object?&gt;</c> + <c>ExportConfiguration</c>
/// shape the existing <c>IExcelExportService</c> already understands (via
/// <see cref="ReportColumnDefinition.ToExportColumn"/>), so the ClosedXML
/// generator/styling is reused verbatim — zero duplicate spreadsheet code.
///
/// "Report Header, Company Logo, Generated By, Generated Date, Applied Filters,
/// Summary Information" are realized as banner/title rows built from
/// <see cref="ReportResponseDto.GeneratedBy"/>/<see cref="ReportResponseDto.GeneratedAt"/>/
/// <see cref="ReportResponseDto.AppliedFilters"/>/<see cref="ReportResponseDto.SummaryNote"/> —
/// fields that exist on the ONE response envelope precisely so every export carries them
/// without any per-report plumbing.
/// </summary>
public interface IReportExportService
{
    /// <summary>
    /// Generates a branded .xlsx for the given (already fully-resolved, unpaginated)
    /// report response. Returns raw file bytes ready for <c>File(...)</c>.
    /// </summary>
    byte[] GenerateExcel(ReportResponseDto report);

    /// <summary>
    /// Generates RFC-4180 CSV bytes (UTF-8 with BOM for Excel compatibility) for the
    /// given report response — data rows only (CSV has no concept of a styled banner;
    /// the header/filters/summary are instead written as leading comment-style rows
    /// prefixed with "#", which spreadsheet apps display as plain text and most CSV
    /// consumers can skip).
    /// </summary>
    byte[] GenerateCsv(ReportResponseDto report);

    /// <summary>
    /// Convenience entry point used by <c>ReportsController</c>'s export action:
    /// re-runs the report against the FULL filtered set (via
    /// <see cref="IReportService.GetReportForExportAsync"/>) and renders it in the
    /// requested <see cref="ReportExportFormat"/>, returning the bytes and a
    /// suggested file name (without extension — the controller appends it).
    /// </summary>
    Task<(byte[] Bytes, string FileName, string ContentType, string FileExtension)> ExportAsync(
        string key, ReportFilterDto filter, ReportExportFormat format, CancellationToken cancellationToken = default);
}
