using System;
using System.Collections.Generic;

namespace NubeEra.Application.Common.Reporting;

/// <summary>
/// The ONE response shape returned by every report — what
/// <see cref="NubeEra.Application.Interfaces.Services.Reporting.IReportService.GetReportAsync"/>
/// hands back, and what <c>ReportPage</c> on the frontend renders generically
/// (KPI cards, grid, charts, applied-filter chips, pagination) regardless of
/// which of the 18 categories it is. No per-report response DTOs exist anywhere
/// in the framework — this is the single contract.
/// </summary>
public class ReportResponseDto
{
    /// <summary>Stable report key (e.g. "student-attendance-summary") — round-tripped so the frontend can re-request/export without re-resolving the menu.</summary>
    public string Key { get; set; } = null!;

    /// <summary>Menu category this report belongs to (one of the 18 — e.g. "Student Reports").</summary>
    public string Category { get; set; } = null!;

    public string Title { get; set; } = null!;
    public string? Description { get; set; }

    /// <summary>Ordered grid column metadata — drives <c>ReportGrid</c> AND (via <see cref="ReportColumnDefinition.ToExportColumn"/>) every export.</summary>
    public List<ReportColumnDefinition> Columns { get; set; } = new();

    /// <summary>Page of already-authorized, already-filtered/sorted rows, one dictionary per row keyed by column <see cref="ReportColumnDefinition.Key"/> — same shape the Excel export framework already uses, so both pipelines share one row contract.</summary>
    public List<Dictionary<string, object?>> Rows { get; set; } = new();

    /// <summary>Total matching rows BEFORE pagination — required for the grid's pager and to honour "Export only filtered data" (export re-queries with the same filter at the full size).</summary>
    public int TotalCount { get; set; }
    public int Page { get; set; }
    public int PageSize { get; set; }
    public int TotalPages => PageSize <= 0 ? 0 : (int)Math.Ceiling(TotalCount / (double)PageSize);

    /// <summary>Dashboard Analytics — KPI Cards (computed from the same scoped data; never hardcoded).</summary>
    public List<ReportKpiDto> Kpis { get; set; } = new();

    /// <summary>Dashboard Analytics — Charts / Trend / Comparison analysis (Line/Bar/Pie/Donut/Area).</summary>
    public List<ReportChartDto> Charts { get; set; } = new();

    /// <summary>Echo of the (RBAC-adjusted) filter that produced this response — rendered as "Applied Filters" chips on screen and baked into every export's header banner.</summary>
    public ReportFilterDto AppliedFilters { get; set; } = new();

    /// <summary>UTC timestamp the report was generated — becomes the export's "Generated Date".</summary>
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    /// <summary>Display name of the requesting user — becomes the export's "Generated By".</summary>
    public string? GeneratedBy { get; set; }

    /// <summary>Free-form summary line(s) a provider may surface above the grid (e.g. "187 of 4,302 students shown — filtered by Grade 8, Term 2"). Optional; purely descriptive.</summary>
    public string? SummaryNote { get; set; }
}

/// <summary>
/// Lightweight metadata describing one registered report for menu/listing
/// purposes (<c>GET /api/reports</c>) — deliberately excludes data so the menu
/// can be built without running every report's query.
/// </summary>
public class ReportDefinitionSummaryDto
{
    public string Key { get; set; } = null!;
    public string Category { get; set; } = null!;
    public string Title { get; set; } = null!;
    public string? Description { get; set; }
}

/// <summary>
/// What an <see cref="NubeEra.Application.Interfaces.Services.Reporting.IReportDataProvider"/>
/// returns from its single data-access method — everything
/// <see cref="NubeEra.Application.Services.Reporting.ReportService"/> needs to
/// assemble the final <see cref="ReportResponseDto"/> (it adds the envelope:
/// Key/Category/Title/Columns/AppliedFilters/GeneratedAt/GeneratedBy/paging echo).
/// </summary>
public class ReportDataResult
{
    public List<Dictionary<string, object?>> Rows { get; set; } = new();
    public int TotalCount { get; set; }
    public List<ReportKpiDto> Kpis { get; set; } = new();
    public List<ReportChartDto> Charts { get; set; } = new();
    public string? SummaryNote { get; set; }

    public static ReportDataResult Empty() => new();
}
