using System.ComponentModel.DataAnnotations.Schema;
using NubeEra.Domain.Common;

namespace NubeEra.Domain.Entities;

public class Student : BaseEntity
{
    public Guid SchoolId { get; set; }
    public Guid GradeId { get; set; }
    public Guid? UserId { get; set; }
    public string StudentId { get; set; } = null!;   // auto-generated by service if not supplied
    public string? RollNo { get; set; }
    public string FirstName { get; set; } = null!;
    public string LastName { get; set; } = null!;
    public string? Email { get; set; }   // optional — null when no login account
    [NotMapped]
    public string FullName => $"{FirstName} {LastName}";
    public string? Phone { get; set; }
    public DateTime? DateOfBirth { get; set; }
    public string? Gender { get; set; }
    public string? BloodGroup { get; set; }
    public string? Address { get; set; }
    public DateTime? AdmissionDate { get; set; }
    public string? ParentGuardianName { get; set; }
    public string? ParentGuardianPhone { get; set; }
    public string? ParentGuardianEmail { get; set; }
    public string? EmergencyContact { get; set; }
    public string? ProfilePictureUrl { get; set; }
    public string? PersonalNote { get; set; }
    public bool IsActive { get; set; } = true;

    /// <summary>Nullable — existing students without a section remain valid.</summary>
    public Guid? SectionId { get; set; }

    // Navigation Properties
    public School        School   { get; set; } = null!;
    public Grade         Grade    { get; set; } = null!;
    public User?         User     { get; set; }
    public GradeSection? Section  { get; set; }
    public ICollection<StudentSubject> StudentSubjects { get; set; } = new List<StudentSubject>();
}
