using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using NubeEra.Application.Common.Export;
using NubeEra.Application.Common.Reporting;
using NubeEra.Application.Interfaces.Services.Export;
using NubeEra.Application.Interfaces.Services.Reporting;

namespace NubeEra.Infrastructure.Services.Reporting;

/// <summary>
/// The ONE export pipeline for the Reporting module (directive's <c>ReportExportService</c>).
/// Deliberately thin: Excel generation is delegated entirely to the existing,
/// already-shared <see cref="IExcelExportService"/> (same ClosedXML engine the
/// Students/Teachers export pilot uses) — this class only re-shapes a
/// <see cref="ReportResponseDto"/> into that engine's <see cref="ExportConfiguration"/>
/// contract and adds the report-specific banner (title/branding/applied filters/
/// generated-by/date/summary). CSV is the one genuinely new format here, written
/// directly (CSV has no styling concept, so no shared engine is warranted).
///
/// PDF/Print: intentionally NOT generated server-side. No PDF-rendering library
/// exists anywhere in this solution (csproj inspected — only ClosedXML, EF Core,
/// JWT, BCrypt). Rather than bolt on an unverified dependency, the directive's
/// "PDF, Print" requirements are satisfied client-side: the same on-screen
/// <c>ReportPage</c> (already showing the branded header/filters/KPIs/grid) is
/// rendered to a dedicated print stylesheet and produced via the browser's
/// native print-to-PDF — which is both zero-dependency and pixel-faithful to
/// what the user is already looking at. See <c>ReportExport</c> component notes.
/// </summary>
public class ReportExportService : IReportExportService
{
    private static readonly Encoding Utf8WithBom = new UTF8Encoding(encoderShouldEmitUTF8Identifier: true);

    private readonly IReportService _reportService;
    private readonly IExcelExportService _excelExportService;

    public ReportExportService(IReportService reportService, IExcelExportService excelExportService)
    {
        _reportService = reportService;
        _excelExportService = excelExportService;
    }

    public async Task<(byte[] Bytes, string FileName, string ContentType, string FileExtension)> ExportAsync(
        string key, ReportFilterDto filter, ReportExportFormat format, CancellationToken cancellationToken = default)
    {
        // Re-run against the FULL filtered set (not just the on-screen page) —
        // "Export only filtered data" means every matching row, not page N of it.
        var report = await _reportService.GetReportForExportAsync(key, filter, cancellationToken);
        var fileNameBase = BuildFileName(report);

        return format switch
        {
            ReportExportFormat.Csv => (GenerateCsv(report), fileNameBase, "text/csv", "csv"),
            _ => (GenerateExcel(report), fileNameBase, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"),
        };
    }

    public byte[] GenerateExcel(ReportResponseDto report)
    {
        if (report is null) throw new ArgumentNullException(nameof(report));

        var configuration = ExportConfiguration.Create(
            fileName: BuildFileName(report),
            sheetName: report.Title,
            columns: report.Columns
                .Where(c => !c.GridOnly)
                .Select(c => c.ToExportColumn()),
            title: BuildTitleBanner(report));

        return _excelExportService.GenerateExcel(report.Rows, configuration);
    }

    public byte[] GenerateCsv(ReportResponseDto report)
    {
        if (report is null) throw new ArgumentNullException(nameof(report));

        var columns = report.Columns.Where(c => !c.GridOnly).ToList();
        var sb = new StringBuilder();

        // CSV has no banner concept — emit the same "Report Header / Generated By /
        // Generated Date / Applied Filters / Summary" data as leading "#" comment
        // rows. Spreadsheet apps render these as plain text in column A; most CSV
        // consumers either ignore "#"-prefixed lines or simply show them as data —
        // either way no information from the directive's required header is lost.
        AppendCommentLine(sb, $"Report: {report.Title}");
        if (!string.IsNullOrWhiteSpace(report.Description)) AppendCommentLine(sb, report.Description!);
        AppendCommentLine(sb, $"Generated By: {report.GeneratedBy ?? "—"}");
        AppendCommentLine(sb, $"Generated Date: {report.GeneratedAt:yyyy-MM-dd HH:mm} UTC");
        AppendCommentLine(sb, $"Applied Filters: {DescribeFilters(report.AppliedFilters)}");
        if (!string.IsNullOrWhiteSpace(report.SummaryNote)) AppendCommentLine(sb, $"Summary: {report.SummaryNote}");
        AppendCommentLine(sb, $"Total Records: {report.TotalCount}");
        sb.Append('\n');

        sb.AppendLine(string.Join(",", columns.Select(c => CsvEscape(c.Header))));

        foreach (var row in report.Rows)
        {
            var values = columns.Select(c => CsvEscape(FormatCellForCsv(row.TryGetValue(c.Key, out var v) ? v : null, c)));
            sb.AppendLine(string.Join(",", values));
        }

        return Utf8WithBom.GetBytes(sb.ToString());
    }

    // ── Banner / naming / formatting helpers ─────────────────────────────────

    private static string BuildTitleBanner(ReportResponseDto report)
    {
        // Single multi-segment banner string — ExcelExportService merges this
        // across the header row as one cell, so newlines render as wrapped lines
        // within that cell (ClosedXML respects '\n' when wrap text is enabled,
        // and the shared engine already enables it for title banners).
        var lines = new List<string>
        {
            report.Title,
            $"Generated By: {report.GeneratedBy ?? "—"}   |   Generated: {report.GeneratedAt:yyyy-MM-dd HH:mm} UTC   |   Records: {report.TotalCount}",
            $"Applied Filters: {DescribeFilters(report.AppliedFilters)}"
        };

        if (!string.IsNullOrWhiteSpace(report.SummaryNote))
        {
            lines.Add(report.SummaryNote!);
        }

        return string.Join("\n", lines);
    }

    /// <summary>
    /// Renders the applied <see cref="ReportFilterDto"/> as a short human-readable
    /// summary for the export banner — exactly the directive's "Applied Filters"
    /// requirement. Only non-empty members are listed so an unfiltered report
    /// reads "All records" rather than a wall of "— : (none)".
    /// </summary>
    internal static string DescribeFilters(ReportFilterDto filter)
    {
        if (filter is null) return "All records";

        var parts = new List<string>();

        if (filter.SchoolId.HasValue) parts.Add($"School: {filter.SchoolId}");
        if (!string.IsNullOrWhiteSpace(filter.AcademicYear)) parts.Add($"Academic Year: {filter.AcademicYear}");
        if (filter.DateFrom.HasValue || filter.DateTo.HasValue)
        {
            parts.Add($"Date: {(filter.DateFrom?.ToString("yyyy-MM-dd") ?? "…")} to {(filter.DateTo?.ToString("yyyy-MM-dd") ?? "…")}");
        }
        if (filter.Month.HasValue) parts.Add($"Month: {filter.Month}");
        if (filter.Quarter.HasValue) parts.Add($"Quarter: Q{filter.Quarter}");
        if (filter.Year.HasValue) parts.Add($"Year: {filter.Year}");
        if (filter.GradeId.HasValue) parts.Add($"Grade: {filter.GradeId}");
        if (filter.SubjectId.HasValue) parts.Add($"Subject: {filter.SubjectId}");
        if (filter.CourseId.HasValue) parts.Add($"Course: {filter.CourseId}");
        if (filter.BatchId.HasValue) parts.Add($"Batch: {filter.BatchId}");
        if (filter.StudentId.HasValue) parts.Add($"Student: {filter.StudentId}");
        if (filter.ParentId.HasValue) parts.Add($"Parent: {filter.ParentId}");
        if (filter.TeacherId.HasValue) parts.Add($"Teacher: {filter.TeacherId}");
        if (filter.StaffId.HasValue) parts.Add($"Staff: {filter.StaffId}");
        if (filter.PrincipalId.HasValue) parts.Add($"Principal: {filter.PrincipalId}");
        if (!string.IsNullOrWhiteSpace(filter.Status)) parts.Add($"Status: {filter.Status}");
        if (!string.IsNullOrWhiteSpace(filter.Search)) parts.Add($"Search: \"{filter.Search}\"");
        if (!string.IsNullOrWhiteSpace(filter.SavedFilterName)) parts.Add($"Saved Filter: {filter.SavedFilterName}");
        if (filter.AdvancedFilters is { Count: > 0 })
        {
            parts.AddRange(filter.AdvancedFilters.Select(kv => $"{kv.Key}: {kv.Value}"));
        }

        return parts.Count == 0 ? "All records" : string.Join("  •  ", parts);
    }

    private static string BuildFileName(ReportResponseDto report)
    {
        var slug = (report.Key ?? report.Title ?? "report")
            .ToLowerInvariant()
            .Select(ch => char.IsLetterOrDigit(ch) ? ch : '-')
            .Aggregate(new StringBuilder(), (acc, ch) => acc.Append(ch))
            .ToString();

        while (slug.Contains("--")) slug = slug.Replace("--", "-");
        slug = slug.Trim('-');

        return $"{slug}-{report.GeneratedAt:yyyyMMdd-HHmm}";
    }

    private static void AppendCommentLine(StringBuilder sb, string text) => sb.Append('#').Append(' ').AppendLine(text);

    private static string FormatCellForCsv(object? value, ReportColumnDefinition column)
    {
        if (value is null) return string.Empty;

        return column.Type switch
        {
            ReportColumnType.Date when value is DateTime dt => dt.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture),
            ReportColumnType.DateTime when value is DateTime dtm => dtm.ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture),
            ReportColumnType.Percent when value is IFormattable pf => pf.ToString("0.0", CultureInfo.InvariantCulture) + "%",
            ReportColumnType.Currency when value is IFormattable cf => cf.ToString("0.00", CultureInfo.InvariantCulture),
            ReportColumnType.Boolean when value is bool b => b ? "Yes" : "No",

            _ => value?.ToString() ?? string.Empty
        };
    }

    private static string CsvEscape(string? value)
    {
        value ??= string.Empty;
        var needsQuoting = value.Contains(',') || value.Contains('"') || value.Contains('\n') || value.Contains('\r');
        if (!needsQuoting) return value;

        return "\"" + value.Replace("\"", "\"\"") + "\"";
    }
}
