import React, { useEffect, useRef, useState } from 'react';
import { ChevronDown, Download, FileSpreadsheet, FileText, Loader2, Printer } from 'lucide-react';
import { useReportExport } from '../../hooks/useReport';
import type { ReportExportFormat, ReportFilter } from '../../services/reportService';

export interface ReportExportProps {
  reportKey: string;
  /** The CURRENT applied filter — exporting always re-runs against the full filtered set server-side ("Export only filtered data"), never just the on-screen page. */
  filter: ReportFilter;
  /** Friendly report title — used in the downloaded filename and toast feedback. */
  title: string;
  className?: string;
}

const FORMATS: { format: ReportExportFormat; label: string; icon: React.ElementType; hint: string }[] = [
  { format: 'excel', label: 'Excel (.xlsx)', icon: FileSpreadsheet, hint: 'Full filtered set, server-generated workbook' },
  { format: 'csv', label: 'CSV', icon: FileText, hint: 'Full filtered set, server-generated CSV' },
  { format: 'pdf', label: 'PDF', icon: FileText, hint: 'Opens your browser\'s print dialog — pick "Save as PDF" as the destination' },
  { format: 'print', label: 'Print', icon: Printer, hint: 'Prints the report exactly as shown, with header & filters' },
];

/**
 * ReportExport — the ONE export control every report screen renders.
 *
 * Offers all four formats the directive mandates (Excel/CSV/PDF/Print) behind
 * a single button, routed entirely through `useReportExport`/`reportService`:
 * Excel and CSV stream the full filtered dataset from the same generic
 * `IReportExportService` engine the backend exposes once
 * (`POST /reports/{key}/export`); PDF and Print are deliberately client-side
 * (`window.print()`) so they capture the exact on-screen report — including
 * the report header, applied-filter chips, KPI summary, and "Generated by/at"
 * stamp `ReportPage` renders in a `print:`-only header — rather than standing
 * up a second PDF layout engine. This is the export half of "Do NOT create
 * separate report engines."
 */
const ReportExport: React.FC<ReportExportProps> = ({ reportKey, filter, title, className = '' }) => {
  const { isExporting, runExport } = useReportExport();
  const [open, setOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const onClick = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) setOpen(false);
    };
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false);
    };
    document.addEventListener('mousedown', onClick);
    document.addEventListener('keydown', onKeyDown);
    return () => {
      document.removeEventListener('mousedown', onClick);
      document.removeEventListener('keydown', onKeyDown);
    };
  }, [open]);

  const handlePick = async (format: ReportExportFormat) => {
    setOpen(false);
    await runExport(reportKey, filter, format, title);
  };

  return (
    <div className={`relative ${className}`} ref={menuRef}>
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        disabled={isExporting}
        title={`Export ${title}`}
        aria-label={`Export ${title}`}
        aria-haspopup="menu"
        aria-expanded={open}
        className="bg-white dark:bg-[#1e293b] border border-slate-200 dark:border-[#334155] text-slate-700 dark:text-[#e2e8f0] px-4 py-2.5 rounded-[4px] font-bold uppercase tracking-widest text-[10px] hover:bg-slate-50 dark:hover:bg-[#283548] hover:border-primary/40 hover:text-primary transition-all outline-none flex items-center justify-center gap-1.5 shadow-sm disabled:opacity-60 disabled:cursor-not-allowed"
      >
        {isExporting ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
        {isExporting ? 'Exporting…' : 'Export'}
        <ChevronDown className={`w-3 h-3 transition-transform ${open ? 'rotate-180' : ''}`} />
      </button>

      {open && (
        <div role="menu" aria-orientation="vertical" aria-label={`Export ${title} options`} className="absolute right-0 mt-2 w-64 bg-white dark:bg-[#1e293b] border border-slate-200 dark:border-[#334155] rounded-xl shadow-xl z-20 overflow-hidden py-1.5">
          {FORMATS.map(({ format, label, icon: Icon, hint }) => (
            <button
              key={format}
              type="button"
              role="menuitem"
              onClick={() => handlePick(format)}
              className="w-full text-left px-4 py-2.5 hover:bg-slate-50 dark:hover:bg-[#283548] focus:bg-slate-50 dark:focus:bg-[#283548] transition-colors flex items-start gap-3 outline-none"
            >
              <Icon className="w-4 h-4 text-primary mt-0.5 shrink-0" />
              <span className="flex flex-col">
                <span className="text-xs font-bold text-slate-700 dark:text-[#e2e8f0]">{label}</span>
                <span className="text-[10px] text-slate-400 dark:text-[#64748b] leading-snug">{hint}</span>
              </span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
};

export default ReportExport;
