import React, { useMemo } from 'react';
import {
  AlertCircle, Award, Banknote, BarChart3, BookOpen, Briefcase, Calendar, CalendarCheck, CalendarClock,
  CalendarDays, CheckCircle, ClipboardList, FileCheck, FileText, GraduationCap, LogIn, Receipt, ScrollText,
  Shield, ShoppingCart, TrendingUp, Trophy, UserCheck, UserPlus, Users, XCircle, type LucideIcon,
} from 'lucide-react';
import { useReport } from '../../hooks/useReport';
import ReportFilterBar, { type ReportFilterFieldOption } from './ReportFilter';
import ReportGrid from './ReportGrid';
import ReportChartCard from './ReportChart';
import ReportExport from './ReportExport';
import StatGridCards from '@/components/StatGrid';
import type { ReportFilter as ReportFilterState, ReportKpi } from '../../services/reportService';

/** Maps the icon-name strings the backend's `ReportKpiDto` factories attach (e.g. "Users", "TrendingUp") onto the matching lucide-react component. Unknown names fall back to BarChart3 — KPIs always render, never crash, even if a future provider names an icon this map hasn't seen yet. */
const KPI_ICONS: Record<string, LucideIcon> = {
  Users, UserCheck, TrendingUp, CalendarCheck, CheckCircle, XCircle, FileText, Award, ShoppingCart,
  DollarSign: Banknote, Receipt, ScrollText, Shield, LogIn, Calendar, ClipboardList, UserPlus, BookOpen,
  FileCheck, CalendarClock, Trophy, GraduationCap, Briefcase, CalendarDays, Currency: Banknote,
};

function formatKpiValue(kpi: ReportKpi): string {
  switch (kpi.format) {
    case 'percent': return `${kpi.value}%`;
    case 'currency': return kpi.value.toLocaleString(undefined, { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
    case 'decimal': return kpi.value.toLocaleString(undefined, { maximumFractionDigits: 2 });
    default: return Math.round(kpi.value).toLocaleString();
  }
}

const KPI_COLORS = ['sky', 'indigo', 'violet', 'teal'] as const;

export interface ReportPageProps {
  /** Provider key, e.g. "student-attendance" — the only thing that differs between the 18 categories' report screens. */
  reportKey: string;
  /** Seed filter values fixed for this screen (e.g. a parent's own child, a teacher's own classes). Merged once on mount. */
  initialFilter?: Partial<ReportFilterState>;
  /** Sort-by choices surfaced in the filter bar — must match column keys the provider sorts on. */
  sortOptions?: ReportFilterFieldOption[];
  /** Status choices surfaced as a dropdown instead of free-text search. */
  statusOptions?: ReportFilterFieldOption[];
  /** Hide the date-range filter for reports with no date dimension. */
  showDateRange?: boolean;
}

/**
 * ReportPage — the ONE screen every report in all 18 categories renders.
 *
 * This is the load-bearing piece of "Do NOT create separate report engines /
 * Avoid duplicate implementations": a category page is nothing more than
 * `<ReportPage reportKey="student-attendance" .../>`. Everything — fetching
 * (`useReport`), filtering (`ReportFilter`), the KPI strip, charts
 * (`ReportChart`), the results grid (`ReportGrid`), and export
 * (`ReportExport`) — is wired here exactly once. Extending to report #19
 * never touches this file.
 *
 * Also renders the export-framework's mandated report header — title,
 * description, "Generated by ... at ...", the applied-filter echo, and the
 * `summary_note` — both on screen and (via `print:` utility classes) as the
 * literal header PDF/Print captures, so "Report Header / Company Logo /
 * Generated By & Date / Applied Filters / Summary" appears in every export
 * path without a single format-specific layout.
 */
const ReportPage: React.FC<ReportPageProps> = ({ reportKey, initialFilter, sortOptions, statusOptions, showDateRange = true }) => {
  const { filter, setFilter, setPage, setPageSize, reset, data, isLoading, error, refetch } = useReport({ reportKey, initialFilter });

  const handleSortChange = (sortBy: string) => {
    if (filter.sort_by === sortBy) {
      setFilter({ sort_direction: filter.sort_direction === 'asc' ? 'desc' : 'asc' });
    } else {
      setFilter({ sort_by: sortBy, sort_direction: 'asc' });
    }
  };

  const appliedFilterChips = useMemo(() => {
    const f = data?.applied_filters ?? filter;
    const chips: string[] = [];
    if (f.search) chips.push(`Search: "${f.search}"`);
    if (f.date_from) chips.push(`From: ${f.date_from.slice(0, 10)}`);
    if (f.date_to) chips.push(`To: ${f.date_to.slice(0, 10)}`);
    if (f.status) chips.push(`Status: ${f.status}`);
    if (f.academic_year) chips.push(`Year: ${f.academic_year}`);
    if (f.sort_by) chips.push(`Sorted by ${f.sort_by} (${f.sort_direction ?? 'asc'})`);
    return chips;
  }, [data, filter]);

  const generatedAt = data?.generated_at ? new Date(data.generated_at) : null;

  return (
    <div className="space-y-6 print:space-y-4">
      {/* Report header — Title / description / company branding / generated-by stamp / summary. Captured as-is by PDF/Print. */}
      <div className="bg-gradient-to-br from-white via-slate-50/50 to-indigo-50/10 dark:from-[#1e293b] dark:to-[#0f172a]/60 border border-slate-200 dark:border-[#334155] rounded-3xl p-6 shadow-sm flex flex-col gap-4 print:shadow-none print:border-slate-300">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-primary/10 to-primary/20 flex items-center justify-center shrink-0 print:hidden shadow-inner">
              <BarChart3 className="w-6 h-6 text-primary animate-pulse" />
            </div>
            <div>
              <div className="text-[10px] font-black uppercase tracking-widest text-primary mb-1 print:text-slate-500">
                {data?.category ?? 'Report'}
              </div>
              <h1 className="text-xl font-black text-slate-900 dark:text-white tracking-tight">{data?.title ?? 'Loading report…'}</h1>
              {data?.description && <p className="text-xs text-slate-500 dark:text-[#94a3b8] mt-1.5 max-w-3xl leading-relaxed">{data.description}</p>}
            </div>
          </div>
          <div className="flex items-center gap-2 print:hidden">
            {data && <ReportExport reportKey={reportKey} filter={filter} title={data.title} />}
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-x-6 gap-y-2 text-[11px] text-slate-500 dark:text-[#94a3b8] border-t border-slate-100 dark:border-[#283548] pt-4">
          {generatedAt && (
            <span>
              Generated by <span className="font-bold text-slate-700 dark:text-[#e2e8f0]">{data?.generated_by ?? 'System'}</span> on{' '}
              <span className="font-bold text-slate-700 dark:text-[#e2e8f0]">{generatedAt.toLocaleString()}</span>
            </span>
          )}
          {typeof data?.total_count === 'number' && (
            <span><span className="font-bold text-slate-700 dark:text-[#e2e8f0]">{data.total_count.toLocaleString()}</span> records found</span>
          )}
        </div>

        {appliedFilterChips.length > 0 && (
          <div className="flex flex-wrap gap-2 mt-1">
            {appliedFilterChips.map((chip) => (
              <span key={chip} className="text-[10px] font-bold px-3 py-1 rounded-full bg-slate-100/80 dark:bg-[#283548]/80 text-slate-600 dark:text-[#cbd5e1] border border-slate-200/50 dark:border-[#334155]/50">
                {chip}
              </span>
            ))}
          </div>
        )}

        {data?.summary_note && (
          <div className="text-xs font-semibold text-slate-600 dark:text-[#cbd5e1] bg-slate-50/60 dark:bg-[#283548]/30 rounded-2xl px-4 py-3 border border-slate-100 dark:border-[#334155] mt-1">
            {data.summary_note}
          </div>
        )}
      </div>

      {error && (
        <div className="bg-rose-50 dark:bg-rose-950/30 border border-rose-200 dark:border-rose-900 rounded-2xl p-5 flex items-center gap-3 text-rose-700 dark:text-rose-300">
          <AlertCircle className="w-5 h-5 shrink-0" />
          <div className="flex-1">
            <p className="text-sm font-bold">Couldn&apos;t run this report</p>
            <p className="text-xs">{error}</p>
          </div>
          <button
            type="button"
            onClick={refetch}
            className="text-[10px] font-bold uppercase tracking-widest px-3 py-2 rounded-lg border border-rose-300 dark:border-rose-800 hover:bg-rose-100 dark:hover:bg-rose-900/40 transition-colors"
          >
            Retry
          </button>
        </div>
      )}

      {/* Filters */}
      <div className="print:hidden">
        <ReportFilterBar
          filter={filter}
          onChange={setFilter}
          onReset={reset}
          sortOptions={sortOptions}
          statusOptions={statusOptions}
          showDateRange={showDateRange}
          isLoading={isLoading}
        />
      </div>

      {/* KPI strip — Dashboard Analytics: KPI Cards / Summary Statistics, all sourced from the SAME filtered dataset as the grid below. */}
      {data && data.kpis.length > 0 && (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 print:grid-cols-4">
          <StatGridCards stats={data.kpis.map((kpi, idx) => {
            const Icon = (kpi.icon && KPI_ICONS[kpi.icon]) || BarChart3;
            return {
              title: kpi.label,
              value: formatKpiValue(kpi),
              color: KPI_COLORS[idx % KPI_COLORS.length],
              icon: <Icon className="w-5 h-5" />
            };
          })} />
        </div>
      )}

      {/* Charts — Dashboard Analytics: Line/Bar/Pie/Donut/Area + Trend/Comparison Analysis, computed server-side from the same scoped query. */}
      {data && data.charts.length > 0 && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 print:hidden">
          {data.charts.map((chart) => <ReportChartCard key={chart.key} chart={chart} />)}
        </div>
      )}

      {/* Results grid — server-side sorted/paginated, "Export only filtered data" semantics shared with ReportExport. */}
      {data && (
        <ReportGrid
          columns={data.columns}
          rows={data.rows}
          totalCount={data.total_count}
          filter={filter}
          onSortChange={handleSortChange}
          onPageChange={setPage}
          onPageSizeChange={setPageSize}
          isLoading={isLoading}
        />
      )}
    </div>
  );
};

export default ReportPage;
